import { Theme } from "../theme.slint";
import { Store } from "../store.slint";
import { Logic } from "../logic.slint";
import { IconBtn } from "../base/icon-btn.slint";
import { Divider } from "../base/divider.slint";

export component Footer inherits Rectangle {
    width: 100%;
    height: 30px;

    VerticalLayout {
        Divider {
            background: red;
        }
        Rectangle {
            background: green;
        }
    }
}

