import { Theme } from "../theme.slint";
import { Store } from "../store.slint";
import { Logic } from "../logic.slint";
import { Util } from "../util.slint";
import { Label } from "../base/label.slint";
import { Divider } from "../base/divider.slint";

export component Footer inherits Rectangle {
    width: 100%;
    height: 30px;

    VerticalLayout {
        Divider {}

        Rectangle {
            background: Theme.lighter-border-color;
            HorizontalLayout {
                alignment: start;
                spacing: Theme.spacing * 4;

                Label {
                    text: Store.translator.btc-price + ": $" + Util.format-number-with-commas(Store.btc-info.price);
                }

                Label {
                    text: Store.translator.btc-per-byte-fee + ": " + Store.btc-info.byte-fee-slow + "/" + Store.btc-info.byte-fee-normal + "/" + Store.btc-info.byte-fee-fast;
                }
            }
        }
    }
}

