import { Theme } from "../theme.slint";
import { Store } from "../store.slint";
import { Logic } from "../logic.slint";
import { Label } from "../base/label.slint";
import { IconBtn } from "../base/icon-btn.slint";
import { Divider } from "../base/divider.slint";

export component Header inherits Rectangle {
    height: Theme.header-height;
    background: Theme.lighter-border-color;

    callback show-network-setting;
    callback flush-account;

    HorizontalLayout {
        HorizontalLayout {
            padding-left: Theme.padding;

            Rectangle {
                address-label := Label {
                    width: parent.width;
                    text: Store.account.address;
                    overflow: elide;
                }
            }

        }

        right-hlayout := HorizontalLayout {
             VerticalLayout {
                alignment: center;
                HorizontalLayout {
                    spacing: Theme.spacing * 2;
                    IconBtn {
                        width: Theme.icon-size * 1.33;
                        icon-width: Theme.icon-size;
                        icon: @image-url("../images/copy.svg");
                        tip-pos: "left";
                        tip-text: Store.translator.tip-copy;
                        clicked => {
                            Logic.copy-to-clipboard(Store.account.address);
                        }
                    }

                    IconBtn {
                        width: Theme.icon-size * 1.33;
                        icon-width: Theme.icon-size * 0.8;
                        icon: @image-url("../images/reset.svg");
                        tip-pos: "left";
                        tip-text: Store.translator.tip-flush;
                        clicked => {
                            root.flush-account();
                        }
                    }

                    IconBtn {
                        width: Theme.icon-size * 1.33;
                        icon-width: Theme.icon-size;
                        icon: @image-url("../images/network.svg");
                        tip-pos: "left";
                        tip-text:  {
                            if (Store.account.network == "main") {
                                Store.translator.tip-main-network;
                            } else {
                                Store.translator.tip-test-network;
                            }

                        }
                        clicked => {
                            root.show-network-setting();
                        }
                    }
                }
            }

            VerticalLayout {
                alignment: center;
                padding-left: Theme.padding * 2;
                padding-right: Theme.padding * 2;

                Divider {
                    width: 2px;
                    height: root.height * 0.5;
                    background: Theme.base-border-color;
                }
            }

            VerticalLayout {
                alignment: center;
                HorizontalLayout {
                    spacing: Theme.spacing * 2;
                    IconBtn {
                        width: Theme.icon-size * 1.33;
                        icon: @image-url("../images/setting-fill.svg");
                        tip-pos: "left";
                        tip-text: Store.translator.tip-setting;
                        clicked => {
                            Store.setting-dialog-config.show = true;
                        }
                    }

                    IconBtn {
                        width: Theme.icon-size * 1.33;
                        icon: @image-url("../images/help.svg");
                        tip-pos: "left";
                        tip-text: Store.translator.tip-help;
                        clicked => {
                            Store.help-dialog.show = true;
                        }
                    }

                    IconBtn {
                        width: Theme.icon-size * 1.33;
                        icon: @image-url("../images/info-dark.svg");
                        tip-pos: "left";
                        tip-text: Store.translator.tip-about;
                        clicked => {
                            Store.about-dialog.show = true;
                        }
                    }
                }
            }
        }
    }
}
