import { Theme } from "../../theme.slint";
import { Avatar } from "../../base/avatar.slint";
import { Store } from "../../store.slint";
import { Logic } from "../../logic.slint";
import { Btn } from "../../base/btn.slint";

export component BFile inherits HorizontalLayout {
    in-out property<string> uuid;
    in-out property<string> file-id;
    in-out property<string> name;
    in-out property<string> size;
    in-out property<string> status;

    alignment: start;
    spacing: Theme.padding * 2;
    padding-left: Theme.scroll-width;

    pure function get-status(status: string) -> string{
        if (status == "undownload") {
            return Store.translator.undownload;
        } else if (status == "downloading") {
            return Store.translator.downloading;
        } else if (status == "downloaded") {
            return Store.translator.downloaded;
        } else if (status == "download-failed") {
            return Store.translator.download-failed;
        }

        return Store.translator.error;
    }

    pure function status-color(status: string) -> color {
        if (status == "downloading") {
            return Theme.brand-color.darker(50%);
        } else if (status == "downloaded") {
            return Theme.success-color.darker(50%);
        } else if (status == "download-failed") {
            return Theme.warning-color.darker(50%);
        }

        return Theme.basic-black-color;
    }

    av := Avatar {
        icon-source: @image-url("../../images/bot.svg");
    }

    Rectangle {
        width: 450px;
        background: Theme.dark-fill-color;
        border-color: Theme.darker-border-color;
        border-radius: Theme.border-radius;
        border-width: 1px;

        HorizontalLayout {
            padding: Theme.padding * 2;
            spacing: Theme.spacing * 2;

            img := Image {
                width: 80px;
                source: @image-url("../../images/file.svg");
            }

            VerticalLayout {
                padding: Theme.padding;
                name-txt := Text {
                    text: Store.translator.file-name + "  " + root.name;
                    overflow: elide;
                }

                size-txt := Text {
                    text: Store.translator.file-size + "  " + root.size;
                }

                status-txt := Text {
                    color: root.status-color(root.status);
                    text: Store.translator.file-status + "  " + root.get-status(root.status);
                }

                HorizontalLayout {
                    alignment: center;
                    padding-top: Theme.padding * 4;

                    Btn {
                        width: 100%;
                        border-radius: Theme.border-radius;
                        text: Store.translator.file-download;
                        icon: @image-url("../../images/download.svg");

                        clicked => {
                            Logic.download-file(root.uuid, root.file-id, root.name);
                        }
                    }

                }
            }
        }
    }
}
