import { Theme } from "../../theme.slint";
import { Avatar } from "../../base/avatar.slint";
import { Store } from "../../store.slint";
import { Logic } from "../../logic.slint";
import { IconBtn } from "../../base/icon-btn.slint";

export component BImage inherits HorizontalLayout {
    in-out property image <=>  img.source;
    in-out property<string> image-path;
    property<float> image-rate: 0.3;

    alignment: start;
    spacing: Theme.padding * 2;
    padding-left: Theme.scroll-width;

    av := Avatar {
        icon-source: @image-url("../../images/bot.svg");
    }

    Rectangle {
        height: img.height;
        width: img.width;
        background: Theme.dark-border-color;
        border-radius: Theme.border-radius;

        img := Image {
            width: Math.min(root.width * image-rate, root.width - root.spacing * 2 - av.width - root.padding-left);
        }

        Rectangle {
            x: parent.width - self.width - Theme.padding * 2;
            y: Theme.spacing * 2;
            width: hbox.preferred-width + Theme.padding * 2;
            height: hbox.preferred-height + Theme.padding * 2;
            background: Theme.base-fill-color;
            border-radius: Theme.border-radius;
            opacity: 0.5;

            hbox := HorizontalLayout {
                x: Theme.padding;
                y: Theme.padding;
                spacing: Theme.padding * 2;

                IconBtn {
                    bg-color: Colors.transparent;
                    colorize: Theme.basic-black-color;
                    icon: @image-url("../../images/zoom-in.svg");
                    tip-text: Store.translator.tip-zoom-in;

                    clicked => {
                        image-rate = 1;
                    }
                }

                IconBtn {
                    bg-color: Colors.transparent;
                    colorize: Theme.basic-black-color;
                    icon: @image-url("../../images/zoom-out.svg");
                    tip-text: Store.translator.tip-zoom-out;

                    clicked => {
                        image-rate = 0.3;
                    }
                }

                IconBtn {
                    bg-color: Colors.transparent;
                    colorize: Theme.basic-black-color;
                    icon: @image-url("../../images/download.svg");
                    tip-text: Store.translator.tip-download;

                    clicked => {
                        Logic.save-image(root.image-path);
                    }
                }
            }
        }
    }
}
