import { ListView } from "std-widgets.slint";
import { Theme } from "../../theme.slint";
import { Store } from "../../store.slint";
import { Logic } from "../../logic.slint";
import { UItem } from "./uitem.slint";
import { BItem } from "./bitem.slint";
import { Timestamp } from "./timestamp.slint";
import { UImage } from "./uimage.slint";
import { BImage } from "./bimage.slint";
import { UFile } from "./ufile.slint";
import { BFile } from "./bfile.slint";
import { NoMessageImg } from "../../base/no-message.slint";
import { CenterLayout } from "../../base/center-layout.slint";

export component Body inherits Rectangle {
    in-out property viewport-y <=> lv.viewport-y;
    in-out property viewport-height <=> lv.viewport-height;

    public function scroll-to-top() {
        lv.viewport-y = 0;
    }

    public function scroll-to-bottom() {
        if (lv.viewport-height <= lv.visible-height) {
            return;
        }

        lv.viewport-y = -lv.viewport-height + lv.visible-height;
    }

    public function scroll-up() {
        if (lv.viewport-y + lv.visible-height/4 >= 0) {
            lv.viewport-y = 0;
        } else {
            lv.viewport-y = lv.viewport-y + lv.visible-height/4;
        }
    }

    public function scroll-down() {
        if (lv.viewport-height <= lv.visible-height ||
                lv.viewport-y <= -lv.viewport-height + lv.visible-height) {
            return;
        }

        if (lv.viewport-y - lv.visible-height/4 <= -lv.viewport-height) {
            lv.viewport-y = -lv.viewport-height + lv.visible-height;
        } else {
            lv.viewport-y = lv.viewport-y - lv.visible-height/4;
        }
    }

    public function jump-to-viewport-y(vy: length) {
        if (vy < -lv.viewport-height + lv.visible-height) {
            lv.viewport-height = -vy + lv.visible-height;
        }

        lv.viewport-y = vy;
    }

    public function is-chats-on-bottom() -> bool {
        lv.viewport-y <= -lv.viewport-height + (lv.visible-height * 1.2);
    }

    NoMessageImg {
        visible: Store.session-datas.length <= 0;
        width: 500px;
        text: Store.translator.no-message;
    }

    lv := ListView {
        width: root.width; height: root.height;
        for data[index] in Store.session-datas : VerticalLayout {
            padding-top: Theme.padding * 2;
            padding-bottom: Theme.padding * 2;
            spacing: Theme.spacing * 2;

            if data.type == "timestamp" : Timestamp {
                text: data.text;
            }
            if data.type == "uitem" : UItem {
                text: data.text;
            }

            if data.type == "bitem" : BItem {
                text: data.text;
            }

            if data.type == "uimage": UImage {
                image: data.img;
            }

            if data.type == "bimage": BImage {
                image: data.img;
                image-path: data.img-path;
            }

            if data.type == "ufile": UFile {
                uuid: data.uuid;
                name: data.file-name;
                size: data.file-size;
            }

            if data.type == "bfile": BFile {
                uuid: data.uuid;
                file-id: data.file-id;
                name: data.file-name;
                status: data.file-status;
                size: data.file-size;
            }
        }
    }
}
