import { Theme } from "../../theme.slint";
import { Avatar } from "../../base/avatar.slint";
import { Store } from "../../store.slint";
import { Logic } from "../../logic.slint";
import { IconBtn } from "../../base/icon-btn.slint";

export component UImage inherits HorizontalLayout {
    in-out property image <=>  img.source;
    property<float> image-rate: 0.3;

    alignment: end;
    spacing: Theme.padding * 2;

    Rectangle {
        height: img.height;
        width: img.width;
        background: Theme.dark-border-color;
        border-radius: Theme.border-radius;

        img := Image {
            width: Math.min(root.width * image-rate, root.width - root.spacing * 2 - av.width);
        }

        Rectangle {
            x: Theme.padding * 2;
            y: Theme.spacing * 2;
            width: hbox.preferred-width + Theme.padding * 2;
            height: hbox.preferred-height + Theme.padding * 2;
            background: Theme.base-fill-color;
            border-radius: Theme.border-radius;
            opacity: 0.5;

            hbox := HorizontalLayout {
                x: Theme.padding;
                y: Theme.padding;
                spacing: Theme.padding * 2;

                IconBtn {
                    bg-color: Colors.transparent;
                    colorize: Theme.basic-black-color;
                    icon: @image-url("../../images/zoom-in.svg");
                    tip-text: Store.translator.tip-zoom-in;

                    clicked => {
                        image-rate = 1;
                    }
                }

                IconBtn {
                    bg-color: Colors.transparent;
                    colorize: Theme.basic-black-color;
                    icon: @image-url("../../images/zoom-out.svg");
                    tip-text: Store.translator.tip-zoom-out;

                    clicked => {
                        image-rate = 0.3;
                    }
                }
            }
        }
    }

    av := Avatar {
        icon-source: Store.setting-dialog-config.chat.user-avatar;
    }
}
