import { Theme } from "../theme.slint";
import { Store } from "../store.slint";

export global PFunc  {
    pure public function get-status(status: string) -> string {
        if (status == "Online" || status == "在线") {
            return Store.translator.online;
        } else if (status == "Busy" || status == "正忙") {
            return Store.translator.busy;
        } else if (status == "Idle" || status == "空闲") {
            return Store.translator.idle;
        } else if (status == "Offline") {
            return Store.translator.offline;
        }

        return status;
    }

    pure public function get-status-color(status: string) -> color {
        if (status == "Online" || status == "在线") {
            return Theme.success-color;
        } else if (status == "Busy" || status == "正忙") {
            return Theme.warning-color;
        } else if (status == "Idle" || status == "空闲") {
            return Theme.info-color;
        } else if (status == "Offline") {
            return Theme.danger-color;
        }

        return Theme.brand-color;
    }
}
