import { Theme } from "../theme.slint";
import { Divider } from "../base/divider.slint";
import { Header } from "./header.slint";
import { Body } from "./body.slint";

export component LPanel inherits Rectangle {
    width: Theme.left-panel-width;
    clip: true;

    callback avatar-clicked <=> header.avatar-clicked;

    animate width {
        duration: Theme.default-animate-duration;
        easing: ease-in-out;
    }

    VerticalLayout {
        spacing: Theme.spacing;
        header := Header { }
        Body { }
    }
}

