import { Theme } from "./theme.slint";
import { Logic } from "./logic.slint";
import { BaseLogic } from "./base/logic.slint";
import { Store } from "./store.slint";
import { Util } from "./util.slint";
import { Translator } from "./translator.slint";
import { ChatItem, ChatSession, Store } from "./store.slint";
import { MDItem } from "./base/data.slint";
import { Blanket } from "./base/blanket.slint";
import { LPanel } from "./leftPanel/panel.slint";
import { RPanel } from "./rightPanel/panel.slint";
import { Message } from "./base/message.slint";
import { SettingDialog } from "./dialog/setting/dialog.slint";
import { AboutDialog } from "./dialog/about.slint";
import { HelpDialog } from "./dialog/help.slint";
import { OkCancelDialog } from "./dialog/ok-cancel.slint";
import { IconBtn } from "./base/icon-btn.slint";

export component AppWindow inherits Window {
    default-font-size: Theme.default-font-size;
    default-font-family: Theme.default-font-family;
    preferred-width: Theme.default-width;
    preferred-height: Theme.default-height;
    background: Theme.base-background;
    icon: @image-url("./images/icon.png");
    forward-focus: fscope;
    title: "gossipbox";

    public function is-chats-on-bottom() -> bool {
        return rpanel.is-chats-on-bottom();
    }

    public function chats-scroll-to-bottom() {
        rpanel.scroll-to-bottom();
    }

    init => {
        rpanel.focus();
    }

    fscope := FocusScope {
        property <bool> is-ctrl-pressed: false;
        key-pressed(event) => {
            if (event.text == Key.Control) {
                is-ctrl-pressed = true;
            } else if (event.text == Key.Escape) {
                modal.hide();
            }

            if (is-ctrl-pressed) {
                if (event.text == ",") {
                    Theme.toggle-sessions-panel();
                } else if (event.text == "i") {
                    rpanel.focus();
                }
            }
            accept
        }

        key-released(event) => {
            if (event.text == Key.Control) {
                is-ctrl-pressed = false;
            }
            accept
        }

        HorizontalLayout {
            LPanel {
                avatar-clicked => {
                    Store.setting-dialog-config.show = true;
                    setting-dialog.show-chat-setting();
                }
            }
            rpanel := RPanel { }
        }

        modal := Rectangle {
            function hide() {
                if (about-dialog.visible) {
                    Store.about-dialog.show = false;
                } else if (help-dialog.visible) {
                    Store.help-dialog.show = false;
                }
            }

            if setting-dialog.visible || oc-dialog.visible || about-dialog.visible || help-dialog.visible : low-modal := Blanket { }

            setting-dialog := SettingDialog {
                close => {
                    rpanel.focus();
                }
            }

            oc-dialog := OkCancelDialog { }
            about-dialog := AboutDialog { }
            help-dialog := HelpDialog { }
        }

        msg := Message {
            x: root.width / 2 - self.width / 2;
            y: 50px;
            text: Store.message.text;
            type: Store.message.text-type;
            clicked => {
                Logic.copy-to-clipboard(self.text);
            }
        }
    }
}

export { Util, Logic, BaseLogic, ChatItem, ChatSession, Store }
