import { SettingDialogConfig } from "./store.slint";

export global Logic {
    callback hide-window();
    callback show-message(string, string);
    callback copy-to-clipboard(string);
    callback handle-ok-cancel-dialog(string, string);

    callback clean-cache();

    callback setting-cancel();
    callback setting-ok(SettingDialogConfig);

    callback flush-account();
    callback switch-network();

    callback set-send-address(string); // argument: address
    callback address-book-add-item(string, string); // argument: name, address
    callback address-book-delete-item(string); // argument: uuid
    callback address-book-item-address(string) -> string; // argument: uuid

    callback activity-delete-item(string); // argument: uuid

    callback delete-account(string); // argument: uuid;
    callback show-mnemonic(string); // argument: uuid;

    pure callback pretty-btc-price(string) -> string; // argument: price; return: format price
    pretty-btc-price(price) => { return price; }
}

