import { Translator, Translation} from "./translator.slint";
import { MDItem } from "./base/data.slint";

export struct Account {
    uuid: string,
    name: string,
    address: string,
    network: string,
    balance-btc: string,
    balance-usd: string,
}

export struct AddressBookItem {
    uuid: string,
    name: string,
    address: string,
}

export struct BtcInfo {
    price: string,
    byte-fee-slow: string,
    byte-fee-normal: string,
    byte-fee-fast: string,
}

export struct MessageItem {
    text: string,
    text-type: string,
}

export struct OkCancelDialogSetting {
    title-type: string,
    title-text: string,
    body-text: string,
    handle-type: string,
    handle-uuid: string,
}

export struct SettingUI {
    font-size: string,
    font-family: string,
    win-width: string,
    win-height: string,
    language: string,
}

export struct SettingProxy {
    enabled: bool,
    url: string,
    port: string,
}

export struct SettingDialogConfig {
    show: bool,
    ui: SettingUI,
    proxy: SettingProxy,
}

export struct AboutDialog {
    show: bool,
    title: string,
    text: string,
    sponsor: string,
}

export global Store  {
    in-out property<Account> account: {
        uuid: "default-uuid",
        name: "account-1",
        address: "tb1qq8jfvz4fzc83jrysyrtj83sn4ps0zenwjcetrl",
        network: "test",
        balance-btc: "100.11",
        balance-usd: "1000000",
    };

    in-out property<bool> is-show-address-book-add-item-dialog: false;
    in-out property<bool> is-show-address-book-qrcode-dialog: false;

    in-out property<[AddressBookItem]> address-book-datas: [
        {
            uuid: "uuid-1",
            name: "name-1",
            address: "address-1",
        },
        {
            uuid: "uuid-2",
            name: "name-2wjifjwifjwifjwifjweifjweif",
            address: "address-2wjfowefjwifjwifjwijfwi jfwiefjwi",
        },
    ];

    in-out property<BtcInfo> btc-info: {
        price: "654321",
        byte-fee-slow: "10",
        byte-fee-normal: "25",
        byte-fee-fast: "40",
    };

    in-out property<MessageItem> message;
    in-out property<OkCancelDialogSetting> ok-cancel-dialog-setting;

    in-out property<SettingDialogConfig> setting-dialog-config: {
        show: false,
        ui: {
            font-size: "18",
            font-family: "SourceHanSerifCN",
            win-width: "500",
            win-height: "550",
            language: "cn",
        },
        proxy: {
            enabled: false,
            url: "127.0.0.1",
            port: "1080",
        }
    };

    in-out property<AboutDialog> about-dialog: {
        show: false,
        title: "BitBox v0.0.1",
        text: "Based on Slint-UI. Copyright 2022-2030 The Heng30 Company Ltd. All rights reserved. The program is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.",
        sponsor: "0xf1199999751b1a3A74590adBf95401D19AB30014",
    };

    in-out property<Translation> translator: Translator.translation(setting-dialog-config.ui.language == "cn");

    in-out property<{show: bool, text-cn: string, text-en: string}> help-dialog: {
        show: false,
        text-cn:
              "配置和数据:\n"
            + "  1. 配置保存在~/.config/bitbox目录下。\n"
            + "  2. 数据保存在~/.local/share/bitbox目录下。\n",

        text-en:
              "Configuration And Data:\n"
            + "  1. Configuration is stored in the ~/.config/bitbox directory.\n"
            + "  2. Data is stored in the ~/.local/share/bitbox directory.\n",
    };
}
