import { LineEdit, ComboBox } from "std-widgets.slint";
import { Theme } from "../../theme.slint";
import { Store } from "../../store.slint";
import { Logic } from "../../logic.slint";
import { Label } from "../../base/label.slint";
import { Btn } from "../../base/btn.slint";

export component Chat inherits VerticalLayout {
    in-out property user-name <=> username-le.text;
    in-out property user-status <=> status-combox.current-value;

    VerticalLayout {
        spacing: Theme.spacing * 4;
        alignment: start;

        HorizontalLayout {
            Label {
                width: Theme.default-label-width;
                text: Store.translator.setting-dialog-chat-username;
            }

            username-le := LineEdit {
                text: Store.setting-dialog-config.chat.user-name;
            }
        }

        HorizontalLayout {
            Label {
                width: Theme.default-label-width;
                text: Store.translator.setting-dialog-chat-status;
            }

            status-combox := ComboBox {
                model: [Store.translator.setting-dialog-chat-online, Store.translator.setting-dialog-chat-busy, Store.translator.setting-dialog-chat-idle];
                current-value: self.model[0];
                current-index: 0;
            }
        }

        HorizontalLayout {
            padding-top: Theme.padding * 4;
            Btn {
                bg-color: Theme.danger-color;
                border-radius: Theme.border-radius;
                text: Store.translator.setting-dialog-chat-cache-clean + "(" + Store.setting-dialog-config.chat.cache-size + ")";
                icon: @image-url("../../images/warning.svg");
                clicked => {
                    Logic.clean-cache();
                }
            }
        }
    }
}
